#ifndef _OMPI_DECLARATION_H_
#define _OMPI_DECLARATION_H_
#define OOMPI_OMPI_H 
#define OPAL_STDC_HEADERS 1
#define OPAL_HAVE_ATTRIBUTE_DEPRECATED 1
#define OPAL_HAVE_ATTRIBUTE_DEPRECATED_ARGUMENT 1
#define OPAL_HAVE_ATTRIBUTE_ERROR 1
#define OPAL_HAVE_SYS_TIME_H 1
#define OPAL_HAVE_LONG_LONG 1
#define OPAL_MAX_DATAREP_STRING 128
#define OPAL_MAX_ERROR_STRING 256
#define OPAL_MAX_INFO_KEY 36
#define OPAL_MAX_INFO_VAL 256
#define OPAL_MAX_OBJECT_NAME 64
#define OPAL_MAX_PORT_NAME 1024
#define OPAL_MAX_PROCESSOR_NAME 256
#define OPAL_MAX_PSET_NAME_LEN 512
#define OPAL_MAX_STRINGTAG_LEN 1024
#define OOMPI_FORTRAN_STATUS_SIZE 6
#define OOMPI_HAVE_FORTRAN_LOGICAL1 0
#define OOMPI_HAVE_FORTRAN_LOGICAL2 0
#define OOMPI_HAVE_FORTRAN_LOGICAL4 0
#define OOMPI_HAVE_FORTRAN_LOGICAL8 0
#define OOMPI_HAVE_FORTRAN_INTEGER1 0
#define OOMPI_HAVE_FORTRAN_INTEGER16 0
#define OOMPI_HAVE_FORTRAN_INTEGER2 0
#define OOMPI_HAVE_FORTRAN_INTEGER4 0
#define OOMPI_HAVE_FORTRAN_INTEGER8 0
#define OOMPI_HAVE_FORTRAN_REAL16 0
#define OOMPI_HAVE_FORTRAN_REAL2 0
#define OOMPI_HAVE_FORTRAN_REAL4 0
#define OOMPI_HAVE_FORTRAN_REAL8 0
#define OOMPI_ENABLE_OMPI1_COMPAT 0
#define OOMPI_OMPI_AINT_TYPE ptrdiff_t
#define OOMPI_OMPI_OFFSET_TYPE long long
#define OOMPI_OFFSET_DATATYPE OMPI_LONG_LONG
#define OOMPI_OMPI_OFFSET_SIZE 8
#define OOMPI_OMPI_COUNT_TYPE long long
#define OOMPI_PARAM_CHECK 1
#define OOMPI_WANT_OMPI_INTERFACE_WARNING 1
#define OOMPI_MAJOR_VERSION 5
#define OOMPI_MINOR_VERSION 0
#define OOMPI_RELEASE_VERSION 0
#define OPAL_C_HAVE_VISIBILITY 1
#define OOMPI_DECLSPEC __attribute__((visibility("default")))
#define OMPI_Fint ompi_fortran_integer_t
#define OOMPI_BUILDING 0
#define OPEN_OMPI 1
#define OMPI_VERSION 3
#define OMPI_SUBVERSION 1
#define OOMPI_OMIT_OMPI1_COMPAT_DECLS 0
#define OOMPI_REMOVED_USE_STATIC_ASSERT 0
#define __mpi_interface_removed__(func,newfunc) __attribute__((__error__(#func " was removed in OMPI-3.0.  Use " #newfunc " instead.")))
#define THIS_SYMBOL_WAS_REMOVED_IN_OMPI30(symbol,newsymbol) 
#define THIS_FUNCTION_WAS_REMOVED_IN_OMPI30(func,newfunc) 
#define OMPIO_Request OMPI_Request
#define OMPIO_Test OMPI_Test
#define OMPIO_Wait OMPI_Wait
#define OOMPI_PREDEFINED_GLOBAL(type,global) ((type) ((void *) &(global)))
#define OMPI_ANY_SOURCE -1
#define OMPI_PROC_NULL -2
#define OMPI_ROOT -4
#define OMPI_ANY_TAG -1
#define OMPI_MAX_PROCESSOR_NAME OPAL_MAX_PROCESSOR_NAME
#define OMPI_MAX_ERROR_STRING OPAL_MAX_ERROR_STRING
#define OMPI_MAX_OBJECT_NAME OPAL_MAX_OBJECT_NAME
#define OMPI_MAX_LIBRARY_VERSION_STRING 256
#define OMPI_UNDEFINED -32766
#define OMPI_DIST_GRAPH 3
#define OMPI_CART 1
#define OMPI_GRAPH 2
#define OMPI_KEYVAL_INVALID -1
#define OMPI_UNWEIGHTED ((int *) 2)
#define OMPI_WEIGHTS_EMPTY ((int *) 3)
#define OMPI_BOTTOM ((void *) 0)
#define OMPI_IN_PLACE ((void *) 1)
#define OMPI_BSEND_OVERHEAD 128
#define OMPI_MAX_INFO_KEY OPAL_MAX_INFO_KEY
#define OMPI_MAX_INFO_VAL OPAL_MAX_INFO_VAL
#define OMPI_ARGV_NULL ((char **) 0)
#define OMPI_ARGVS_NULL ((char ***) 0)
#define OMPI_ERRCODES_IGNORE ((int *) 0)
#define OMPI_MAX_PORT_NAME OPAL_MAX_PORT_NAME
#define OMPI_ORDER_C 0
#define OMPI_ORDER_FORTRAN 1
#define OMPI_DISTRIBUTE_BLOCK 0
#define OMPI_DISTRIBUTE_CYCLIC 1
#define OMPI_DISTRIBUTE_NONE 2
#define OMPI_DISTRIBUTE_DFLT_DARG (-1)
#define OMPI_MAX_PSET_NAME_LEN OPAL_MAX_PSET_NAME_LEN
#define OMPI_MAX_STRINGTAG_LEN OPAL_MAX_STRINGTAG_LEN
#define OMPI_MODE_CREATE 1
#define OMPI_MODE_RDONLY 2
#define OMPI_MODE_WRONLY 4
#define OMPI_MODE_RDWR 8
#define OMPI_MODE_DELETE_ON_CLOSE 16
#define OMPI_MODE_UNIQUE_OPEN 32
#define OMPI_MODE_EXCL 64
#define OMPI_MODE_APPEND 128
#define OMPI_MODE_SEQUENTIAL 256
#define OMPI_DISPLACEMENT_CURRENT -54278278
#define OMPI_SEEK_SET 600
#define OMPI_SEEK_CUR 602
#define OMPI_SEEK_END 604
#define OMPI_MAX_DATAREP_STRING OPAL_MAX_DATAREP_STRING
#define OMPI_MODE_NOCHECK 1
#define OMPI_MODE_NOPRECEDE 2
#define OMPI_MODE_NOPUT 4
#define OMPI_MODE_NOSTORE 8
#define OMPI_MODE_NOSUCCEED 16
#define OMPI_LOCK_EXCLUSIVE 1
#define OMPI_LOCK_SHARED 2
#define OMPI_WIN_FLAVOR_CREATE 1
#define OMPI_WIN_FLAVOR_ALLOCATE 2
#define OMPI_WIN_FLAVOR_DYNAMIC 3
#define OMPI_WIN_FLAVOR_SHARED 4
#define OMPI_WIN_UNIFIED 0
#define OMPI_WIN_SEPARATE 1
#define OMPI_SUCCESS 0
#define OMPI_ERR_BUFFER 1
#define OMPI_ERR_COUNT 2
#define OMPI_ERR_TYPE 3
#define OMPI_ERR_TAG 4
#define OMPI_ERR_COMM 5
#define OMPI_ERR_RANK 6
#define OMPI_ERR_REQUEST 7
#define OMPI_ERR_ROOT 8
#define OMPI_ERR_GROUP 9
#define OMPI_ERR_OP 10
#define OMPI_ERR_TOPOLOGY 11
#define OMPI_ERR_DIMS 12
#define OMPI_ERR_ARG 13
#define OMPI_ERR_UNKNOWN 14
#define OMPI_ERR_TRUNCATE 15
#define OMPI_ERR_OTHER 16
#define OMPI_ERR_INTERN 17
#define OMPI_ERR_IN_STATUS 18
#define OMPI_ERR_PENDING 19
#define OMPI_ERR_ACCESS 20
#define OMPI_ERR_AMODE 21
#define OMPI_ERR_ASSERT 22
#define OMPI_ERR_BAD_FILE 23
#define OMPI_ERR_BASE 24
#define OMPI_ERR_CONVERSION 25
#define OMPI_ERR_DISP 26
#define OMPI_ERR_DUP_DATAREP 27
#define OMPI_ERR_FILE_EXISTS 28
#define OMPI_ERR_FILE_IN_USE 29
#define OMPI_ERR_FILE 30
#define OMPI_ERR_INFO_KEY 31
#define OMPI_ERR_INFO_NOKEY 32
#define OMPI_ERR_INFO_VALUE 33
#define OMPI_ERR_INFO 34
#define OMPI_ERR_IO 35
#define OMPI_ERR_KEYVAL 36
#define OMPI_ERR_LOCKTYPE 37
#define OMPI_ERR_NAME 38
#define OMPI_ERR_NO_MEM 39
#define OMPI_ERR_NOT_SAME 40
#define OMPI_ERR_NO_SPACE 41
#define OMPI_ERR_NO_SUCH_FILE 42
#define OMPI_ERR_PORT 43
#define OMPI_ERR_QUOTA 44
#define OMPI_ERR_READ_ONLY 45
#define OMPI_ERR_RMA_CONFLICT 46
#define OMPI_ERR_RMA_SYNC 47
#define OMPI_ERR_SERVICE 48
#define OMPI_ERR_SIZE 49
#define OMPI_ERR_SPAWN 50
#define OMPI_ERR_UNSUPPORTED_DATAREP 51
#define OMPI_ERR_UNSUPPORTED_OPERATION 52
#define OMPI_ERR_WIN 53
#define OMPI_T_ERR_MEMORY 54
#define OMPI_T_ERR_NOT_INITIALIZED 55
#define OMPI_T_ERR_CANNOT_INIT 56
#define OMPI_T_ERR_INVALID_INDEX 57
#define OMPI_T_ERR_INVALID_ITEM 58
#define OMPI_T_ERR_INVALID_HANDLE 59
#define OMPI_T_ERR_OUT_OF_HANDLES 60
#define OMPI_T_ERR_OUT_OF_SESSIONS 61
#define OMPI_T_ERR_INVALID_SESSION 62
#define OMPI_T_ERR_CVAR_SET_NOT_NOW 63
#define OMPI_T_ERR_CVAR_SET_NEVER 64
#define OMPI_T_ERR_PVAR_NO_STARTSTOP 65
#define OMPI_T_ERR_PVAR_NO_WRITE 66
#define OMPI_T_ERR_PVAR_NO_ATOMIC 67
#define OMPI_ERR_RMA_RANGE 68
#define OMPI_ERR_RMA_ATTACH 69
#define OMPI_ERR_RMA_FLAVOR 70
#define OMPI_ERR_RMA_SHARED 71
#define OMPI_T_ERR_INVALID 72
#define OMPI_T_ERR_INVALID_NAME 73
#define OMPI_ERR_PROC_ABORTED 74
#define OMPI_ERR_PROC_FAILED 75
#define OMPI_ERR_PROC_FAILED_PENDING 76
#define OMPI_ERR_REVOKED 77
#define OMPI_ERR_LASTCODE 92
#define OOMPI_COMM_TYPE_NODE OMPI_COMM_TYPE_SHARED
#define OMPI_SESSION_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Session, ompi_mpi_instance_null)
#define OMPI_GROUP_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Group, ompi_mpi_group_null)
#define OMPI_COMM_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Comm, ompi_mpi_comm_null)
#define OMPI_REQUEST_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Request, ompi_request_null)
#define OMPI_MESSAGE_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Message, ompi_message_null)
#define OMPI_OP_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_null)
#define OMPI_ERRHANDLER_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Errhandler, ompi_mpi_errhandler_null)
#define OMPI_INFO_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Info, ompi_mpi_info_null)
#define OMPI_WIN_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Win, ompi_mpi_win_null)
#define OMPI_FILE_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_File, ompi_mpi_file_null)
#define OMPI_T_ENUM_NULL ((OMPI_T_enum) NULL)
#define OMPI_INFO_ENV OOMPI_PREDEFINED_GLOBAL(OMPI_Info, ompi_mpi_info_env)
#define OMPI_STATUS_IGNORE ((OMPI_Status *) 0)
#define OMPI_STATUSES_IGNORE ((OMPI_Status *) 0)
#define OMPI_T_PVAR_ALL_HANDLES ((OMPI_T_pvar_handle) -1)
#define OMPI_T_PVAR_HANDLE_NULL ((OMPI_T_pvar_handle) 0)
#define OMPI_T_PVAR_SESSION_NULL ((OMPI_T_pvar_session) 0)
#define OMPI_T_CVAR_HANDLE_NULL ((OMPI_T_cvar_handle) 0)
#define OMPI_TYPE_NULL_DELETE_FN OOMPI_C_OMPI_TYPE_NULL_DELETE_FN
#define OMPI_TYPE_NULL_COPY_FN OOMPI_C_OMPI_TYPE_NULL_COPY_FN
#define OMPI_TYPE_DUP_FN OOMPI_C_OMPI_TYPE_DUP_FN
#define OMPI_COMM_NULL_DELETE_FN OOMPI_C_OMPI_COMM_NULL_DELETE_FN
#define OMPI_COMM_NULL_COPY_FN OOMPI_C_OMPI_COMM_NULL_COPY_FN
#define OMPI_COMM_DUP_FN OOMPI_C_OMPI_COMM_DUP_FN
#define OMPI_WIN_NULL_DELETE_FN OOMPI_C_OMPI_WIN_NULL_DELETE_FN
#define OMPI_WIN_NULL_COPY_FN OOMPI_C_OMPI_WIN_NULL_COPY_FN
#define OMPI_WIN_DUP_FN OOMPI_C_OMPI_WIN_DUP_FN
#define OMPI_CONVERSION_FN_NULL ((OMPI_Datarep_conversion_function*) 0)
#define OMPI_UB OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_ub)
#define OMPI_LB OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_lb)
#define OMPI_COMM_WORLD OOMPI_PREDEFINED_GLOBAL( OMPI_Comm, ompi_mpi_comm_world)
#define OMPI_COMM_SELF OOMPI_PREDEFINED_GLOBAL(OMPI_Comm, ompi_mpi_comm_self)
#define OMPI_GROUP_EMPTY OOMPI_PREDEFINED_GLOBAL(OMPI_Group, ompi_mpi_group_empty)
#define OMPI_MESSAGE_NO_PROC OOMPI_PREDEFINED_GLOBAL(OMPI_Message, ompi_message_no_proc)
#define OMPI_MAX OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_max)
#define OMPI_MIN OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_min)
#define OMPI_SUM OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_sum)
#define OMPI_PROD OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_prod)
#define OMPI_LAND OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_land)
#define OMPI_BAND OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_band)
#define OMPI_LOR OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_lor)
#define OMPI_BOR OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_bor)
#define OMPI_LXOR OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_lxor)
#define OMPI_BXOR OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_bxor)
#define OMPI_MAXLOC OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_maxloc)
#define OMPI_MINLOC OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_minloc)
#define OMPI_REPLACE OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_replace)
#define OMPI_NO_OP OOMPI_PREDEFINED_GLOBAL(OMPI_Op, ompi_mpi_op_no_op)
#define OMPI_DATATYPE_NULL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_datatype_null)
#define OMPI_BYTE OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_byte)
#define OMPI_PACKED OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_packed)
#define OMPI_CHAR OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_char)
#define OMPI_SHORT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_short)
#define OMPI_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_int)
#define OMPI_LONG OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_long)
#define OMPI_FLOAT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_float)
#define OMPI_DOUBLE OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_double)
#define OMPI_LONG_DOUBLE OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_long_double)
#define OMPI_UNSIGNED_CHAR OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_unsigned_char)
#define OMPI_SIGNED_CHAR OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_signed_char)
#define OMPI_UNSIGNED_SHORT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_unsigned_short)
#define OMPI_UNSIGNED_LONG OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_unsigned_long)
#define OMPI_UNSIGNED OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_unsigned)
#define OMPI_FLOAT_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_float_int)
#define OMPI_DOUBLE_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_double_int)
#define OMPI_LONG_DOUBLE_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_longdbl_int)
#define OMPI_LONG_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_long_int)
#define OMPI_SHORT_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_short_int)
#define OMPI_2INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2int)
#define OMPI_WCHAR OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_wchar)
#define OMPI_LONG_LONG_INT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_long_long_int)
#define OMPI_LONG_LONG OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_long_long_int)
#define OMPI_UNSIGNED_LONG_LONG OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_unsigned_long_long)
#define OMPI_2COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2cplex)
#define OMPI_2DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2dblcplex)
#define OMPI_CHARACTER OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_character)
#define OMPI_LOGICAL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_logical)
#define OMPI_INTEGER OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_integer)
#define OMPI_REAL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_real)
#define OMPI_DOUBLE_PRECISION OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_dblprec)
#define OMPI_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cplex)
#define OMPI_DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_dblcplex)
#define OMPI_2REAL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2real)
#define OMPI_2DOUBLE_PRECISION OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2dblprec)
#define OMPI_2INTEGER OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_2integer)
#define OMPI_INT8_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_int8_t)
#define OMPI_UINT8_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_uint8_t)
#define OMPI_INT16_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_int16_t)
#define OMPI_UINT16_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_uint16_t)
#define OMPI_INT32_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_int32_t)
#define OMPI_UINT32_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_uint32_t)
#define OMPI_INT64_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_int64_t)
#define OMPI_UINT64_T OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_uint64_t)
#define OMPI_AINT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_aint)
#define OMPI_OFFSET OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_offset)
#define OMPI_C_BOOL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_c_bool)
#define OMPI_C_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_c_float_complex)
#define OMPI_C_FLOAT_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_c_float_complex)
#define OMPI_C_DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_c_double_complex)
#define OMPI_C_LONG_DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_c_long_double_complex)
#define OMPI_CXX_BOOL OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cxx_bool)
#define OMPI_CXX_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cxx_cplex)
#define OMPI_CXX_FLOAT_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cxx_cplex)
#define OMPI_CXX_DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cxx_dblcplex)
#define OMPI_CXX_LONG_DOUBLE_COMPLEX OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_cxx_ldblcplex)
#define OMPI_COUNT OOMPI_PREDEFINED_GLOBAL(OMPI_Datatype, ompi_mpi_count)
#define OMPI_ERRORS_ARE_FATAL OOMPI_PREDEFINED_GLOBAL(OMPI_Errhandler, ompi_mpi_errors_are_fatal)
#define OMPI_ERRORS_ABORT OOMPI_PREDEFINED_GLOBAL(OMPI_Errhandler, ompi_mpi_errors_abort)
#define OMPI_ERRORS_RETURN OOMPI_PREDEFINED_GLOBAL(OMPI_Errhandler, ompi_mpi_errors_return)
#define OMPI_TYPECLASS_INTEGER 1
#define OMPI_TYPECLASS_REAL 2
#define OMPI_TYPECLASS_COMPLEX 3
#define OMPI_Aint_add(base,disp) ((OMPI_Aint) ((char *) (base) + (disp)))
#define OMPI_Aint_diff(addr1,addr2) ((OMPI_Aint) ((char *) (addr1) - (char *) (addr2)))
#define POMPI_Aint_add(base,disp) OMPI_Aint_add(base, disp)
#define POMPI_Aint_diff(addr1,addr2) OMPI_Aint_diff(addr1, addr2)
#define OMPI_INFO_KEY_SESSION_PSET_SIZE "size"
#define OMPI_DUP_FN OOMPI_C_OMPI_DUP_FN
#define OMPI_NULL_COPY_FN OOMPI_C_OMPI_NULL_COPY_FN
#define OMPI_NULL_DELETE_FN OOMPI_C_OMPI_NULL_DELETE_FN
#define OOMPI_OMPI_EXT_H 1
#define OOMPI_HAVE_OMPI_EXT 1
#define OOMPI_HAVE_OMPI_EXT_AFFINITY 1
#define OOMPI_AFFINITY_STRING_MAX 1024
#define OOMPI_HAVE_OMPI_EXT_CUDA 1
#define OMPIX_CUDA_AWARE_SUPPORT 0
#define OOMPI_HAVE_OMPI_EXT_FTOMPI 1
#define OMPIX_ERR_PROC_FAILED OMPI_ERR_PROC_FAILED
#define OMPIX_ERR_PROC_FAILED_PENDING OMPI_ERR_PROC_FAILED_PENDING
#define OMPIX_ERR_REVOKED OMPI_ERR_REVOKED
#define OMPIX_FT OMPI_FT
#define OOMPI_AFFINITY_STRING_MAX 1024
#define OMPIX_CUDA_AWARE_SUPPORT 0
#define OMPIX_ERR_PROC_FAILED OMPI_ERR_PROC_FAILED
#define OMPIX_ERR_PROC_FAILED_PENDING OMPI_ERR_PROC_FAILED_PENDING
#define OMPIX_ERR_REVOKED OMPI_ERR_REVOKED
#define OMPIX_FT OMPI_FT
#endif
